name: Build and Run WinForms App
 
on:
  push:
    branches: [main]
 
jobs:
  build-and-run:
    name: Build & Run on Windows
    runs-on: self-hosted  # your self-hosted Windows runner
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
 
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: 'latest'
 
    - name: Build the Solution
      run: msbuild SimpleWinFormsApp.sln /p:Configuration=Release
 
    - name: Run the WinForms App
      run: |
        start "" "$(pwd)\SimpleWinFormsApp\bin\Release\SimpleWinFormsApp.exe"
